const BUTTON_TYPE_DEFAULT = 0;
const BUTTON_TYPE_CTA = 1;
const BUTTON_TYPE_DARK = 2;
const BUTTON_TYPE_SQUARE = 3;
const BUTTON_TYPE_SOCIAL = 4;
const BUTTON_TYPE_OUTLINE = 'outline';
const BUTTON_TYPE_SOLID = 'solid';
const BUTTON_TYPE_CARET = 'caret';
const BUTTON_TYPE_GREY = 'grey';

export {
    BUTTON_TYPE_DEFAULT,
    BUTTON_TYPE_CTA,
    BUTTON_TYPE_DARK,
    BUTTON_TYPE_SQUARE,
    BUTTON_TYPE_SOCIAL,
    BUTTON_TYPE_OUTLINE,
    BUTTON_TYPE_SOLID,
    BUTTON_TYPE_CARET,
    BUTTON_TYPE_GREY
}