const SECTION_ANGLE_NONE = '0';
const SECTION_ANGLE_POSITIVE = '1';
const SECTION_ANGLE_NEGATIVE = '2';
const SECTION_BG_COLOR_WHITE = 'white';
const SECTION_BG_COLOR_GREY = 'grey';
const SECTION_BG_COLOR_DARKBLUE = 'bluedark';
const SECTION_BG_COLOR_BROWN = 'brown';

const SECTION_PADDING_DEFAULT = 'default';
const SECTION_PADDING_BOTTOM_NONE = 'bottom_none';

export {
    SECTION_ANGLE_NONE,
    SECTION_ANGLE_POSITIVE,
    SECTION_ANGLE_NEGATIVE,
    SECTION_BG_COLOR_WHITE,
    SECTION_BG_COLOR_GREY,
    SECTION_BG_COLOR_DARKBLUE,
    SECTION_BG_COLOR_BROWN,

    SECTION_PADDING_DEFAULT,
    SECTION_PADDING_BOTTOM_NONE,
}